# fly.toml app configuration file generated for pears-app on 2023-07-19T15:30:08-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pears-app"
primary_region = "sea"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "immediate"

[env]
  PHX_HOST = "pears-app.fly.dev"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
